In [1]:
print("hello")

hello

In [9]:
import calc
calc.add(5,5)
calc.add(10,15)

25

In [5]:
print(calc.add(5,5))

10

In [14]:
import calc
calc.multiply(6,6)
calc.multiply(8,9)

72

In [15]:
import calc
calc.divide(8,4)
calc.divide(45,9)

5.0

In [17]:
import calc as cc
cc.add(3,3)

6

In [21]:
import math
math.sqrt(81)
math.sqrt(100)

10.0

In [32]:
import random
random.randint(1,10)
random.randint(1,100)

6

In [35]:
import datetime
datetime.datetime.now()

datetime.datetime(2026, 8, 10, 19, 7, 47, 379549)

In [37]:
import sys
sys.version

'3.13.15 (tags/v3.13.15:4061bc4, Aug  5 2026, 13:05:39) [MSC v.1944 64 bit (AMD64)]'

In [39]:
import time
time.sleep(1)

In [41]:
import requests

In [42]:
requests.get("https://www.naver.com")

In [1]:
import pandas as pd

data = {
    '이름' : ['김철수', '이영희', '박민수', '정수진', '최영호', '한미래', '윤지원'],
    '나이' : [25,28,22,31,27,24,29],
    '점수' : [85, 92, 78, 95, 88, 73, 91]
}

In [4]:
df = pd.DataFrame(data)
df.head()

    이름  나이  점수
0  김철수  25  85
1  이영희  28  92
2  박민수  22  78
3  정수진  31  95
4  최영호  27  88

In [7]:
pd.DataFrame(data)

    이름  나이  점수
0  김철수  25  85
1  이영희  28  92
2  박민수  22  78
3  정수진  31  95
4  최영호  27  88
5  한미래  24  73
6  윤지원  29  91

In [11]:
age_mean = int(df['나이'].mean())
age_mean

26

In [13]:
round(int(df['나이'].mean()))

26

In [14]:
df.describe()

              나이         점수
count   7.000000   7.000000
mean   26.571429  86.000000
std     3.101459   7.958224
min    22.000000  73.000000
25%    24.500000  81.500000
50%    27.000000  88.000000
75%    28.500000  91.500000
max    31.000000  95.000000